
=== Sestavení doporučení

Pro vyhodnocení konkrétních doporučení byl vybrán jeden z uživatelů zaměřený téměř výhradně na poslech elektronické hudby. V následujícím přehledu je zobrazeno 20 interpretů s nejvíce poslechy pro tohoto uživatele. Nejvíce poslouchaný interpret je _infected mushroom_ spadající do podžánru _psy trance_, ostatní interpreti, až na _stereo mcs_ a _underworld_) spadají do podžánru _drum&bass_:

[%autofit]
----
+--------------------+-----------+
|          artistName|listenCount|
+--------------------+-----------+
|   infected mushroom|      330.0|
|      chase & status|      323.0|
|       high contrast|      298.0|
|            syncopix|      217.0|
|           aphrodite|      214.0|
|          stereo mcs|      206.0|
|          underworld|      193.0|
|bachelors of science|      168.0|
|  london elektricity|      166.0|
|                  tc|      153.0|
|               cosma|      151.0|
|             nu:tone|      137.0|
|             dj zinc|      123.0|
|             calibre|      115.0|
|              makoto|       99.0|
|              commix|       91.0|
|              bungle|       86.0|
|            pendulum|       86.0|
|           frou frou|       82.0|
|           sub focus|       80.0|
+--------------------+-----------+ 
----

Nejprve si necháme sestavit doporučení nad kompletními vstupními daty a modelem s výchozími hodnotami pro jednotlivé hyper parametry. Z výstupu je patrné, že nám model poskytl relativně uspokojivá doporučení. Všichni interpreti spadají do elektronické hudby. _Drum&bass_ je v doporučení zastoupen ve 40%, ve výběru není žádný interpret z podžánru _psy trance_:

[%autofit]
----
+------------------+
|        artistName|
+------------------+
|     high contrast|
|              krec|
|london elektricity|
|          deadmau5|
|         aphrodite|
|         junkie xl|
|            hybrid|
|         logistics|
|     groove armada|
| nightmares on wax|
+------------------+
----

Další doporučení si necháme sestavit od modelu, který byl vytvořen nad daty, ze kterých byl odebrán dolní 5% kvantil resp. horní 95% kvantil. Tímto jsme z datasetu odebrali extrémní hodnoty a dosáhli tím vyrovnanější distribuce hodnot viz. <<ratings-dist-filtered>>. K vytvoření modelu použijeme optimální hodnoty hyper parametrů viz. <<hp-optimal-values>>. Z výstupu je patrné, že nám model poskytl perfektní doporučení. Všichni intepreti jsou z podžánru _drum&bass_ až na _1200 micrograms_, který patří do žánru _psy trance_. Model doporučuje interprety u kterých tento uživatel nemá žádné poslechny. Oproti modelu s použitými výchozími hodnotami došlo k výraznému kvalitativnímu posunu:

[%autofit]
----
+------------------+
|        artistName|
+------------------+
|         logistics|
|   1200 micrograms|
|     high contrast|
|            john b|
|      concord dawn|
|london elektricity|
|             klute|
|         aphrodite|
|          dj fresh|
|         ltj bukem|
+------------------+
----

Poslední doporučení si necháme sestavit od modelu, u kterého jsme provedli standardizaci hodnot. K vytvoření modelu byla také použita data bez extrémních hodnot viz. <<ratings-dist-filtered>> a optimální hodnoty hyper parametrů viz. <<hp-optimal-values>>. Z výstupu je patrné, že tento model poskytuje zatím nejhorší doporučení, ačkoliv všichni interpreti spadají do elektronické hudby, pouze jediný, _pendulum_, spadá do preferovaných podžánrů. Standaridzace hodnot pravděpodobně zapříčinila pokřivení výsledného modelu:


[%autofit]
----
+--------------------+
|          artistName|
+--------------------+
|         the prodigy|
|the chemical brot...|
|            pendulum|
|                moby|
|         fatboy slim|
|thievery corporation|
|           daft punk|
|            röyksopp|
|   infected mushroom|
|           faithless|
+--------------------+
----