
== Úvod

Podíl online distribuce na celkových objemech neustále roste a to i v segmentech, které byly donedávna doménou kamenných obchodů. Tento růst má za následek tlak, kdy jednotliví obchodníci soupeří o větší podíl na trhu. U většiny úspěšných společností je chování zákazníka pečlivě sledováno. Každý zákazník za sebou zanechává digitální stopu, tato stopa je následně uložena a analyzována. Výsledky takových výpočtů mohou být dále použity pro vylepšení další interakce se zákazníky. Zlepšení uživatelské zkušenosti může nabývat mnoho podob, jedním z nejzřetelnějších je snaha nabídnout zákazníkům takové produkty, které by se jim mohly zamlouvat. 

Množství dat, které je nutné zpracovat je často tak velké, že přesahuje možnosti standartních nástrojů jako jsou například relační databáze. Výpočty takového rozsahu si vyžádaly nové přístupy jak v samotném ukládání dat tak i v jejich následném zpracování. 

V roce 2003 vydala společnost Google dokument Google File System cite:[GFS] popisující strukturu distribuovaného souborového systému GFS, o rok později vydala tatáž společnost dokument MapReduce cite:[MAPRED], popisující jednoduchý programovací model pro paralelní zpracování dat nad GFS. Nejen na základě těchto článků vznikla iniciativa, která měla jako cíl vytvořit volně dostupnou platformu pro zpracování velkých objemů dat. Tento projekt, známý pod jménem Hadoop cite:[HADOOP] aktuálně zahrnuje celý ekosystém nástrojů určených pro široké spektrum použití. Jedná se zejména o HDFS, open source distribuovaný souborový systém. Další z těchto nástrojů je i velice populární univerzální rámec pro paralelní výpočty nad HDFS, Spark cite:[SPARK]. 

Účelem této práce je experimentální aplikace strojového učení na platformě  Spark. Pro experiment byly vybrány doporučovací systémy, konkrétně skupina algoritmů pro kolaborativní filtrování implicitních datasetů. Vybraný algoritmus by měly být implementován s důrazem na paralelní výpočet a škálovatelnost. Pro algoritmus by měla být navržena metodika ohodnocení přesnosti jednotlivých výpočtů. Závěrem budou výsledky posouzeny z hlediska přesnosti, rychlosti a škálovatelnosti.  