
=== Alternating Least Square (ALS)   

ALS z anglického názvu **Alternating Least Squares** volně přeloženo jako *střídavá metoda nejmenších čtverců*. Definujme matici stem:[R_{ui}] kde stem:[u] určuje počet uživatelů a stem:[i] počet položek v katalogu. Elementy stem:[r_{ui} \in \mathbb{R}] matice stem:[R] definují ohodnocení uživatele stem:[u] položky stem:[i]. Předpokládáme, že matice stem:[R] je rozsáhlá ale zároveň velice řídká, typicky méně než 1 % polí má přiřazenou hodnotu. 

[stem]
++++
\begin{align*}
R_{m,n} =
 \begin{pmatrix}
  r_{1,1} & r_{1,2} & \cdots & r_{1,n} \\
  r_{2,1} & r_{2,2} & \cdots & r_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  r_{m,1} & r_{m,2} & \cdots & r_{m,n}
 \end{pmatrix}
\end{align*}
++++ 

Matici stem:[R] rozložíme na 2 matice stem:[X_{ur}] a stem:[Y_{ir}] tak, že stem:[XY^T \approx R]. Tyto matice obsahující radky pro každého uživatele resp. produkt se nazývají faktory. Vektory v těchto faktorových maticích mají typicky nízký počet rozměrů stem:[k]. Každý tento rozměr odpovída latentní vlastnosti modelu a jejich hodnoty odpovídají tomu nakolik jsou uživatelé a produkty spjaty s touto skrytou vlastností <<matrix_factorization>>. Na rozdíl od stem:[R] je vysledná matice stem:[XY^T] hustá, doplněné hodnoty obsahují odhad ohodnocení mezi uživateli a položkami. 
Soustava rovnic daná stem:[XY^T = R] nemá pravděpodobně řešení. Důvodem je příliš mnoho rovnic stem:[u] pro stem:[X] resp. stem:[i] pro stem:[Y] a pouze stem:[k] neznámých. Řešením je použít metodu nejmenších čtverců, kdy hledáme řešení s minimální chybou:

[stem]
++++
\begin{align*}
\lVert R-XY^T \rVert_{2}
\end{align*} 
++++

Na začátku nastavíme hodnoty matice stem:[X] na náhodná malá čísla a spočítáme stem:[Y]. Následně střídavě počítáme stem:[X] a stem:[Y] do té doby, než se stabilizuje hodnota stem:[\lVert R-XY^T \rVert_{2}].