
=== Kolaborativní filtrování pro implicitní datasety

Implicitní data vznikají samotnou interakcí uživatele se systémem. Tato interakce může nabývat mnoho různých podob závislých na konkrétní podobě daného systému. Například pro společnosti poskytující streamovaný obsah jako Netflix nebo Spotify to může být shlédnutí daného obsahu. Ale také zda byl tento obsah shlédnutý celý, zda a kdy bylo shlédnutí přerušeno popřípadě počet shlédnutí. Pro internetové knihkupectví jako Amazon toto budou primárně zakoupené tituly. Tyto data se ukládají a následně vyhodnocují tak aby se dosáhlo co možná nejpřesnějších doporučení. Implicitní data mají tedy tendenci být komplexnější než data explicitní což sebou přináší i řadu problémů, které je nutné v daném algoritmu zohlednit:

1. Pouze pozitivní feedback. Pokud evidujeme pouze položky, které si uživatel vybral, je obtížné rozlišit ty, které opravdu preferuje. Například pokud uživatel neshlédl daný film, může to být způsobeno tím že o něm dosud neví ale také tím, že ho nemá rád.

2. Implicitní datasety obsahují velký podíl šumu. Pokud pasivně sledujeme chování uživatele, můžeme pouze hádat jejich preference a pravé motivy. Například i přesto, že uživatel zhlédl některý film, nemusel se mu doopravdy líbit cite:[CFI].

3. Studený start. Nově přidané produkty do systému mají nulový počet interakcí. Systém by měl být schopný doporučovat i takové produkty.  

Pro tvorbu doporučení na základě kolaborativního filtrování existují dva základní postupy, nacházení nejbližších sousedů a faktorizace matic.   

==== Nacházení nejbližších sousedů

Systémy založené na nacházení nejbližších sousedů se snaží na základě vypočtené vzdálenosti doporučit nejblíže položené položky. Tyto systémy jsou uživatelsky nebo produktově orientované. V prvním případě se vypočítává vzdálenost mezi uživateli ve druhém mezi produkty. Produktově založený přístup je obvykle preferován před uživatelským, podstata produktů se obvykle příliš nemění takže model může být předpočítán a následně použit bez konstantního přepočítávání.






