
=== Spark a Hadoop [[spark-hadoop]]



==== HDFS

Hadoop Distributed File System (HDFS) je distribuovany souiborovy system pro HAdoop. HDFS je optimalizovany pro ukladani velkych objemu dat 
. Pri ukladani dat, HDFS rozdeli soubor do bloku konstantni nakonfigurovane delky, typicky 128 MB a ulozi repliky pro kazdy blok na vikce pocitacu v clustru jednak z duvodu yalohy ale take z duvodu umozneni paralelnich vypoctu nad daty. Kazdy z vypocetnich pocitacu v clustru ma nainstalovanou HDFS sluzbu DataNode. Tato sluzba je zodpovedna za ukladani dat na disk a nasledne zpristupneni techto dat klientum. DataNoda sluzba zna jenom bloky, ktere ma ulozene a jejich identifikatory ale neudrzuje informace o tom, ktere bloky patri ke kterym uloyenym souborum. Tyto infdormace jsou udrzovany koordinacni sluzbou NameNode. NameNode udrzuje informace o mapovani souboru do bloku dale udrzuje metadata o souborech jako jsou naporiklad pristupova prava. 


HDFS je tolerantni k chybam, pokud dojde k havarii disku, pocitace nebo teoreticky v pripade velkych clustru celeho racku. NAmeNode naridi jendnotlivym DataNode slkuzbam, ktere drzi repliky ztracenych dat aby rrozkopirovaly prislusne ztracene bloky na dalsi pocitace v clustru. Tiom se zajisti nastaveny replikacni faktor pro kazdy blok (typicky 3).    

    
==== YARN