

==== Ohodnocení přesnosti modelu

Reálnou přesnost modelu je možné ověřit pouze na datech, které nebyla použita k jeho vytvoření resp. k jeho učení. Obvyklá metoda je rozdělit zdrojový dataset na dvě části, na takzvanou tréningovou a testovací sadu. Model se, jak už název napovídá, učí pouze na tréningove sadě a jeho přesnost se následně ověří na sadě testovací. Obvyklý postup je použít na treningovou sadu 70-80% zdrojových dat. Chyba naměřená na testovací sadě nám ukáže jak by se mohl náš model chovat v reálném nasazení. To, že je chyba naměřená na tréningové sadě nízká a na testovací vysoká může mít několik příčin. Nejpravděpodobnější je, že je náš model takvaně přeučený. To znamená, že je model příliš specilizovaný na tréningovou sadu a nereflektuje realitu. Tento problém je možné eliminovat některým způsobem regularizace cite:[HANDSON(130-137),ISL(215)]. Dalším problémem může být nesprávně zvolená tréningová a testovaci sada, kdy ta testovací obsahuje aspekt, který nebyl zozhledněn v rámci učení. Pro vyhodnocení přesnosti modelu pouzijeme naměřenou hodnotu stem:[y_{i}] a předpovězenou hodnotu modelelu pro dané měření stem:[\hat{y_{i}}]. Rozdíl těchto hodnot odpovídá chybě v předpovědi pro dané měření. Průměrná hodnota přes chyby všech měření nám následně ukáže chybu celkovou. Základní metodiky postavené na tomto pricnipu a pouzívané pro ohodnocení modelu jsou následující:

RMSE (Root Mean Squared Error)::
    Z chyb jednotlivých měření spočítáme druhou mocninu a jejich sumu zprůměrujeme. Celková chyba odpovídá druhé odmocnině z této sumy:

[stem]
++++
\begin{align*}
RMSE = \sqrt{\frac{1}{n}\sum_{i=1}^{n}{(y_{i} - \hat{y_{i}})^2}}
\end{align*}
++++ 
 
MAE (Mean Absolute Error)::  
  Celková chyba odpovídá průměru ze sumy absolutních hodnot chyb jednotlivých měření:

[stem]  
++++
\begin{align*}
MAE = \frac{1}{n}\sum_{i=1}^{n}\left|y_{i} - \hat{y_{i}}\right|
\end{align*}
++++ 

RMSE a MAE jsou si dost podobné kdy ukazují průměrnou chybu nehledě na její orientaci. To znamená, že nezáleži na tom zda je chyba měření kladná nebo zaporná, v obou případech se agreguje do výsledné chyby. RMSE která se zdá v odborné literatuře preferovanější metodikou cite:[HANDSON(109),SDG(487)], více penalizuje velké chyby než MAE. 

==== Hyperparametry

Ve většině případů model obsahuje dodatečné parametry ovlivňující jeho výsledné chování, takzvané hyperparametry. Optimální hodnota těchto parametrů není předem známá a je typicky závislá na podstatě vstupních dat. Tuto hodnotu tedy určujeme  během tréningové fáze. Zde se ale opakuje stejný problém jako při vyčlenění testovacích dat. Při určování hodnoty pouze na jedné sadě dat, neni jisté zda je tato hodnota optimální pouze pro tréningová data nebo obecně. Jedním z postupů jak vyřešit tento problém je vyčlenit další část z treningové sady, takzvanou validační sadu. Přesnost modelu pro různé hodnoty hyperparametrů následně ověřujeme na této sadě. Zde ale uz může docházet k degradaci modelu z důvodu nedostatečnosti treningových dat, kdy jsme se vědomě zbavili poloviny těchto dat   pro dodatečné ověřování přesnosti modelu. Další často používaná metodika je takzvaná křížová validace. Tréningová sada je nejprve rozdělena na sadu stem:[k] stejných částí. Následné provedeme stem:[k] tréningových fází, kdy použijeme stem:[k-1] částí jako trénigovou sadu a jednu část použijeme pro ověření přesnosti. Výsledná průměrná chyba ze všech stem:[k] měření nám poskytne realističtější výslednou hodnotu. Zásadní nevýhodou křížové validace je její nadměrná výpočetní náročnost. Vzorec pro křížovou validaci (KV) s použitím RMSE:

[stem]  
++++
\begin{align*}
RMSE_{KV} = \frac{1}{k}\sum_{i=1}^{k}RMSE_{i}
\end{align*}
++++   


 