
== Vyhodnoceni presnosti modelu

Presnost modelu je mozne overit na pouze datech, ktere nebyly pouzity k jeho vytvoreni resp. k jeho uceni. Obvykla metoda je rozdelit zdrojovy dataset na dve casti, na takzvanou treningovou a testovaci sadu. Model se nasledne trenuje na treningove sade a jeho presnost se overi na testovaci sade. Obvykle se pouziva  80% datasetu na treningovou sadu a zbylych 20% na testovaci sadu. Chyba vznkila na testovaci sade nam ukaze jak se bude nas model chovat v produkcnim nasazeni. Pokud je chyba spociatana na trenigove sade nizka a chyba na testovaci sade vysoka znamena to, ze je nas model preuceny. Pokud nas mocel obsahuje dodatecne parametry - takzvane hyperparametry, jejichz optimalni hodnotu je treba stanovit pomoci dodatecneho testovani, rozdeleni na testovaci a treningovou sadu nemusi stacit. V tomto priopade se obvykla pouziva takzvana krizova validace. Treningova sada je rozdelena na sadu stejnych casti, nasledne je kazdy model trenovan na rozdilne kombinaciu techto casti. Po urceni optimalnich hodnot pro jednotlive  