require 'json'

# REQUIRED:
#  vagrant plugin install vagrant-vbguest
#
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

topology = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'topology.json')))


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

=begin
    tag::box-def[]
    config.vm.box = "centos/7"
    end::box-def[]
=end
    config.vm.box = "../box/package.box"

    #synced folders
    #tag::synced-folders[]
    config.vm.synced_folder '../.',       '/opt/dev',            type: 'nfs'
    config.vm.synced_folder '/yum/repo',  '/var/www/html',       type: 'nfs'
    #end::synced-folders[]
    config.vm.synced_folder '.',          '/tmp/vagrant',        type: 'nfs'                                                                

    #default VM settings
    #tag::vm-settings[]
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 6120] 
        vb.customize ["modifyvm", :id, "--cpus", 2] 
    end
    #end::vm-settings[]

    config.vm.provision "shell", path: "./shell/python.sh"                                                           
    config.vm.provision "shell", path: "./shell/ambari-agent.sh"  
    config.vm.provision "shell", path: "./shell/hadoop-rpm.sh"       

if topology['topology'] == 'multinode' 
#=begin
    # c7202
    #tag::c7202[]
    config.vm.define :c7202 do |c7202|
        c7202.vm.hostname = "c7202.barenode.org"
        c7202.vm.network :private_network, ip: "192.168.72.102"
        c7202.vm.synced_folder '/data/2', '/hadoop/hdfs',        type: 'nfs' 
    end
    #end::c7202[]

    # c7203
    config.vm.define :c7203 do |c7203|
        c7203.vm.hostname = "c7203.barenode.org"
        c7203.vm.network :private_network, ip: "192.168.72.103"
        c7203.vm.synced_folder '/data/3', '/hadoop/hdfs',        type: 'nfs' 
    end

    # c7204
    config.vm.define :c7204 do |c7204|
        c7204.vm.hostname = "c7204.barenode.org"
        c7204.vm.network :private_network, ip: "192.168.72.104"
        c7204.vm.synced_folder '/data/4', '/hadoop/hdfs',        type: 'nfs'   
    end
#=end
end

    #c7201    
    config.vm.define :c7201 do |c7201|       
        c7201.vm.network :private_network, ip: "192.168.72.101"
        c7201.vm.hostname = "c7201.barenode.org"
        c7201.vm.synced_folder '/data/1', '/hadoop/hdfs',        type: 'nfs'   
                                             
        c7201.vm.provider :virtualbox do |vb|
#          vb.customize ["modifyvm", :id, "--memory", 26216] 
#          vb.customize ["modifyvm", :id, "--cpus", 12] 
          vb.customize ["modifyvm", :id, "--memory", 6216] 
          vb.customize ["modifyvm", :id, "--cpus", 3] 
        end        
        
        c7201.vm.provision "shell", path: "./shell/ambari-server.sh" 
        if topology['topology'] == 'multinode' 
            c7201.vm.provision "shell", path: "./shell/ambari-multinode.sh"
        else
            c7201.vm.provision "shell", path: "./shell/ambari-singlenode.sh"
        end 
        c7201.vm.provision "shell", path: "./shell/spark-env.sh"               
        c7201.vm.provision "shell", path: "./shell/asciidoctor.sh"  
        c7201.vm.provision "shell", path: "./shell/jupyter.sh"        
    end 
    
      
end
                        