# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|                                          
  
  # urcuje z ktereho boxu bude virtualni stroj vytvoren
  # v nasem pripade pouzijeme verejne barebone centos7 s podporou puppetu 
  # config.vm.box = "puppetlabs/centos-7.2-64-puppet"
  config.vm.box = "/box/c7/package.box"                 
  
  #konfigurace sdilenych adresaru z hostitelskeho pocitace  
  #adresar kam jsme stahli a robalili repositare pro Ambari a HDP, tytp budo namapovany na cestu /var/www/html
  #tato je pouzita jako vychozi sluzbou httpd (apache web server)
  #dane soubory budou tedy dostupne na lokalnim webovem serveru 
  
  config.vm.synced_folder '/yum/repo', '/var/www/html', type: 'nfs'
  
  
  #vychozi nastavani virtualniho stroje                                 
  #2 jadra a 5GB RAM
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 5120] 
    vb.customize ["modifyvm", :id, "--cpus", 2] 
  end
  
  #nastavani pomoci puppetu
  #toto nastaveni je spolecne pro vsechny uzly v klusteru
  config.vm.provision :puppet do |puppet|
    puppet.environment_path        = "environments"
    puppet.module_path             = "modules"
    puppet.manifests_path          =  "./manifests/"
    puppet.manifest_file           =  "ambari-agent.pp"
    puppet.options = "--verbose --debug"
  end 

  #c7201 je masternode                            
  config.vm.define :c7201 do |c7201|
    
    #c7201.vm.hostname = "c7201.barenode.org"
     config.vm.network "private_network", ip: "192.168.56.101"
    
    #adresar bleprints obsahuje definici jednotlivych sluzeb pro cely kluster       
    c7201.vm.synced_folder './blueprints', '/tmp/vagrant-puppet/blueprints', type: 'nfs'   
    
    c7201.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 10216] 
      vb.customize ["modifyvm", :id, "--cpus", 4] 
    end
    
    #nastavani pomoci puppetu
    #toto nastaveni je specificke pro master node
    c7201.vm.provision :puppet do |puppet|
        puppet.environment_path     = "environments"
        puppet.manifests_path       =  "./manifests/"
        puppet.manifest_file        =  "ambari-server.pp"
    end    
     
  end
        
end
