# REQUIRED:
#  vagrant plugin install vagrant-vbguest
#
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|                                          
  
  # box 
  config.vm.box = "centos/7"
  # config.vm.box = "/dev/vagrant/c72/package.box"    
  
  #synced folders
  config.vm.synced_folder '../.', '/opt/dev', type: 'nfs'


  #defaul VM settings
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 5120] 
    vb.customize ["modifyvm", :id, "--cpus", 2] 
  end
  
  
$script = <<SCRIPT

#!/bin/bash


SCRIPT

  config.vm.provision :shell do |shell|
    shell.inline = $script
  end     
 
      
end
                        