== vyvoj aplikace

Aplikace samotna je vyvinuta v jazyce scala. Scala je nativni jazyk Sparku a pridruzenych knihoven pri vyvoji se tedy budeme mopci inspirovat praktikami pouzitymi pri vyvoji Sparku samotneho. Nejprve bylo nutne vybrat nastroj pro automaticke sestaveni aplikace. Takovy nastroj zkompiluje zdrojove kody nasledne nad nimi spusti projektove junit testy. V pripade, ze se zdreojove kody zkompilouji bez chyby  a testy probehnou bez chyby sestavovaci nastroj vytvori konecnou verzi aplikace. V nasem pripade vytvori standartni java archiv. Pro aplikaci napsanou v jazyce scala existuji dva zakldani nastroje. Prvni sbt (scala build tool) je cisste orientovan na scalu. Druhy Apache Maven je obecny nastroj pro vyvoj aplikaci v jave. Pro nas projekt byl vybran nastroj Apache Maven. Tento je velice flexibilni a dobre zdokumentovany <https://maven.apache.org>. Vsechny projekty pro ktere je pouzity Apache Maven maji jednontnou adresarovou strukturu pro zdrojove kody a pridruzene soubory. Tato struktura je nasledujici:

---
src/
  main/
    resources/   
      <v adresari resources jsou soubory ktere se zahrnou do vysledneho baliku>
    scala/
      <zdrojove soubory aplikace>
  test
    resources/    
      <v adresari resources jsou soubory ktere se zahrnou do vysledneho baliku s testy>
    scala/
      <zdrojove soubory testu aplikace>

---

Dale projekty rizene Apache Maven obsahuji deskriptor projektu. Tento deskriptor je ulozeny v root projektu a ma fixni jemno pom.xml. Tento deskriptor obsahuje nekolik casti, ktere ovlivnuji vyslednou podobu aplikace. Nase aplikace bude obsahovat nasledujici casti:

---
  <groupId>org.barenode</groupId>
  <artifactId>ml-on-spark</artifactId>
  <version>1.0</version>  
  <type>jar</type>
  <name>Strojove ucemni na paltforme Spark</name>
---

Tato sekce obsahuje zakldani informace o projektu. Jemno, verzi a typ. 
Tyto inromace ovlivnuji jak bude cilova aplikace pojmenovana a jakeho bude type. V nasem pripade tesy vznikne java balik se jmenem ml-on-spark-1.0.jar.

---
  <properties>   
    <spark.version>2.4.4</spark.version>
    <java.version>1.8</java.version>    
    <scala.version>2.11.12</scala.version>
  </properties>
---

V sekci properties definujeme promenne pouzite dale v deskriptoru. V nasem pripade tyto promenne opbsahuji verze jednotlivych zavislosti projektu. Aktualni posledni vydana verze Sparku ma cislo 2.4.4, pouzijeme tedy stejne verze javy a scaly, ktere jsou pouzity tam. Pro tuto verzi sparku byla pouzita java 8 a scala 2.11.12.

---
  <dependencies>   
    <!-- scala -->
		<dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
    </dependency>
    
    <!-- spark -->
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
		</dependency>
     
    ...
    
  <dependencies>    
---

Sekce dependencies obsahuje takzvane zavislosti projektu. Realne se jedna o knihovny (jary) na ktere se budemem odkazovat z nasich zdrojovych kodu. Apache Maven pro nas tyto knihvny automaticky stahne a nalinkuje vcetne tranzitivnich zavislosti techto knihoven. Seznam dependenci je rozsahny, uvadime zde tedy pouze zkracenou verzi s knihovnami pro spark a pro scalu.

Dale deskriptor obsahuje definici rozsireni pro scalu. Ve vychozim stavu podporuje Apache MAven pouze javu. Podpora scaly se musi expilictne definovat. Prvni rozsireni scala-maven-plugin aktivuje kompilaci scala zdrojovych souboru. Dalsi rozsireni scalatest-maven-plugin aktivuje podporu junit testu. Tato definice obsahuje dalsi atributy potrebne pro vytvareni lokalnich instanci Sparku pro potreby jednotlivych testu.

Sestaveni aplikace aktivujeme z prikazove radky prikazem:

---
mvn clean install
---

Na konzili se nam naslednbe vypisi informace o uspesnem zkompletovani aplikace:

---
---

V automaticky vytvorenem adresari target je ulozena vysledna aplikace. Tato je zatim prazdna jelikjoz nas projekt zatim nebsahuje zadny zdrojovy kody.