
== Kolaboratni filtrovani pro implicitni datasety

NN. Zakladni SF pristupy jsou zalozene modelovani nejblizsich sousedu.  
TYto modely jsou uziovatelsky nebo polozkove orientovane.
Item based approach is usually preferred over user-based approach. User-based approach is often harder to scale because of the dynamic nature of users, whereas items usually don’t change much, and item based approach often can be computed offline and served without constantly re-training.

Faktorizace matic. Interakce uzivatelu s polozkami jsou definovany jako matice A = {aij} u x v. Kde u je pocet uzivatelu a v je pocet polozek. skalar aij representuje hodnoceni polozky j uzivatelem j. Tato matice je typicky velmi ridka. Ukolem systemu je dopocitat chybejici hodnoty v matici. matrix factorization algorithms work by decomposing the user-item interaction matrix into the product of two lower dimensionality rectangular matrices. One matrix can be seen as the user matrix where rows represent users and columns are latent factors. The other matrix is the item matrix where rows are latent factors and columns represent items.




