
== Kolaboratni filtrovani pro implicitni datasety

Puvodni algoritmy pro kolaborativni filtrovani jsou zalozene nachazeni nejblizsich sousedu. Tyto modely jsou uziovatelsky nebo polozkove orientovane.
Item based approach is usually preferred over user-based approach. User-based approach is often harder to scale because of the dynamic nature of users, whereas items usually don’t change much, and item based approach often can be computed offline and served without constantly re-training.

Faktorizace matic. Interakce uzivatelu s polozkami jsou definovany jako matice A = {aij} u x v. Kde u je pocet uzivatelu a v je pocet polozek. skalar aij representuje hodnoceni polozky j uzivatelem j. Tato matice je typicky velmi ridka. Ukolem systemu je dopocitat chybejici hodnoty v matici. matrix factorization algorithms work by decomposing the user-item interaction matrix into the product of two lower dimensionality rectangular matrices. One matrix can be seen as the user matrix where rows represent users and columns are latent factors. The other matrix is the item matrix where rows are latent factors and columns represent items.

Nevyhody impicitni vazby:

1. Pouze pozitivni feedback. Pokud evidujeme pouze polozky, ktere si uzivatel vybral vybral. Je tezke rozlisit ty ktere ma rad a ty ktere ne. Napriklad pokud uzivatel neshledl dany film, muze byt zpusobeno tim ze o nem zatim nevi ale take tim, ze ho nema rad.

2. Implicitni dataset obsahuje sum. dle [1] pokud pasivne trackujeme chovani uzivatele, muzeme pouze hadat jejich preference a prave motivy. Napriklad i presto ze uzivatel zhledl nektery film, nemusel se mu libit.

3. Studeny start. Nove pridane polozky do systemu majinulovy pocet interakci. System by mel doporucovat i takove polozky.


