
=== Kolaborativní filtrování pro implicitní datasety

Implicitní data vznikají samotnou interakcí uživatele se systémem, mají tedy tendenci být komplexnější. Tento přístup má ale i řadu nevýhod, které je nutné v příslušném algorimtu zohlednit:

1. Pouze pozitivní feedback. Pokud evidujeme pouze položky, které si uživatel vybral, je obtížné rozlišit ty, které opravdu preferuje. Například pokud uživatel neshlédl daný film, může to být způsobeno tím že o něm dosud neví ale také tím, že ho nemá rád.

2. Implicitní datasety obsahují velký podíl *šumu*. Dle [1], pokud pasivně trackujeme chování uživatele, muzeme pouze hádat jejich preference a pravé motivy. Například i přesto, že uživatel zhlédl některý film, nemusel se mu doopravdy líbit.

3. Studený start. Nově přidané produkty do systému mají nulový počet interakcí. Systém by měl být schpný doporučovat i takové produkty.  

Tato práce pokrývá dva základní přístupy kolaborativního filtrování pro implicitní datasety, nacházení *nejbližších sousedů* a *faktorizaci matic*. 

Systémy založené na nacházení nejbližších sousedů se snaží na základě vypočtené vzdálenosti doporučit nejblíže položené položky. Tyto systémy jsou uživatelsky nebo produktově orientované. V prvním případě se vypočítává vzdálenost mezi uživateli ve druhém mezi produkty. Produktově zalozený přístup je obvykle preferován před uživatelským, podstata produktů se obvykle příliš nemění takže model může být předpočítán a následně použit bez kostantního přepočítávání.

V Systémech založených na fakorizaci matic je interakce uzivatelů s produkty definována jako matice stem:[R_{m,n}] kde stem:[m] určuje počet uzivatelů a stem:[n] počet produktů v katalogu. Skalár stem:[R_{ij}] reprezentuje ohodnocení položky stem:[i] uživatelem stem:[j]. Tato matice je typicky velmi řídká. Úkolem algoritmu je dopočítat chybějíci hodnoty v matici. Faktorizace matic je založena na dekompozici matice stem:[R] na několik matic (obvykle dvě) s malým počtem rozměrů. Tyto rozměry reprezentují takzvané *latentní faktory*. Tato práce se bude zabývat dvěmi algoritmy pro fakorizaci matic a to *ALS* a *SVD*.





