:stem: latexmath

== ALS

Definujme matici stem:[R_{m,n}] kde stem:[m] urcuje pocet uzivatelu a stem:[n] pocet polozek v katalogu. Elementy stem:[r_{ij} \in \mathbb{R}] matice stem:[R] definuji ohodnoceni uzivatele stem:[i] polozky stem:[j]. Predpokladame, ze matice stem:[R] je rozsahla ale zaroven velice ridka, vetsinou mene nez 1% poli ma prirazenou hodnotu. 

[stem]
++++
\begin{align*}
R_{m,n} =
 \begin{pmatrix}
  r_{1,1} & r_{1,2} & \cdots & r_{1,n} \\
  r_{2,1} & r_{2,2} & \cdots & r_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  r_{m,1} & r_{m,2} & \cdots & r_{m,n}
 \end{pmatrix}
\end{align*}
++++ 

Matici stem:[R] rozlozime na 2 matice stem:[X_{m,k}] a stem:[Y_{m,k}] tak, ze stem:[XY^T \approx R]. Matice obsahuji radky pro kadeho uzivatele resp. produkt. Radky maji nekolik hodnot stem:[k]. Kazda hodnota odpovida latentni vlastnosti modelu. Kada hodnota v radku odpovida tomu nakolik jsou uzivatele a produkty splaty s touto skrytou vlastnosti [aas:46]. Na rozdil od stem:[R] je vysledna matice stem:[XY^T] husta, doplnene hodnoty obsahuji odhad ohodnoceni mezi uzivateli a polozkami. 

=== LS

[stem]
++++
\begin{align*}
 A^T(b - A\hat{x}) &= 0 \\
 A^TA\hat{x} &= A^Tb  \\
 A\hat{x} &= A(A^TA)^{-1}A^Tb   \\
 P &= A(A^TA)^{-1}A^T 
\end{align*}
++++ 

=== Studie

[stem]
++++
\begin{align*}
 \begin{pmatrix}
  1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\
  3 & 4 & 4 & 5 & 5 & 6 & 7 & 9 \\
  1 & 8 & 2 & 7 & 3 & 6 & 4 & 5 \\
  9 & 8 & 7 & 6 & 5 & 4 & 3 & 2 \\
  9 & 4 & 8 & 3 & 7 & 2 & 6 & 1 \\
  2 & 3 & 2 & 4 & 2 & 5 & 2 & 6 \\
  3 & 4 & 3 & 4 & 4 & 3 & 4 & 3 \\
  3 & 2 & 4 & 3 & 2 & 4 & 3 & 2 \\
  5 & 5 & 4 & 4 & 6 & 6 & 2 & 2 \\
  2 & 3 & 6 & 5 & 4 & 6 & 7 & 2 \\
  1 & 6 & 5 & 3 & 8 & 2 & 3 & 9
  \end{pmatrix}
  =
  \begin{pmatrix}
  1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\
  3 & 4 & 4 & 5 & 5 & 6 & 7 & 9 \\
  1 & 8 & 2 & 7 & 3 & 6 & 4 & 5 \\
  9 & 8 & 7 & 6 & 5 & 4 & 3 & 2 \\
  9 & 4 & 8 & 3 & 7 & 2 & 6 & 1 \\
  2 & 3 & 2 & 4 & 2 & 5 & 2 & 6 \\
  3 & 4 & 3 & 4 & 4 & 3 & 4 & 3 \\
  3 & 2 & 4 & 3 & 2 & 4 & 3 & 2 \\
  5 & 5 & 4 & 4 & 6 & 6 & 2 & 2 \\
  2 & 3 & 6 & 5 & 4 & 6 & 7 & 2 \\
  1 & 6 & 5 & 3 & 8 & 2 & 3 & 9
  \end{pmatrix}
\end{align*}
++++ 